export const User = {
	Id: [
		{
			name: "ibrahim",
			password: "123455",
			email: "ibrahim@gmail.com",
			product: [
				{
					Id: '04',
					Name: "iMouse",
					Brand: "Apple",
					ProductImg: "/assets/Apple/Aplle Watch 7.jpg",
					Ratting: "4/5",
				},
				{
					Id: '05',
					Name: "iphone 10",
					Brand: "Apple",
					ProductImg: "/assets/Apple/iphone 10.jpg",
					Ratting: "4/5",
				},
				{
					Id: '06',
					Name: "Iphone 13",
					Brand: "Apple",
					ProductImg: "/assets/Apple/Iphone 13.jpg",
					Ratting: "5/5",
				},
				{
					Id:'07' ,
					Name: "Samsung Bud",
					Brand: "Samsung",
					ProductImg: "/assets/Samsung/Samsung Bud.jpg",
					Ratting: "4/5",
				},
				{
					Id: '08',
					Name: "Samsung Fold",
					Brand: "Samsung",
					ProductImg: "/assets/Samsung/Samsung Fold.jpg",
					Ratting: "4/5",
				},
				{
					Id:'09',
					Name: "Samsung Laptop",
					Brand: "Samsung",
					ProductImg: "/assets/Samsung/Samsung Laptop.jpg",
					Ratting: "5/5",
				},
				{
					Id: '10',
					Name: "Samsung Phone",
					Brand: "Samsung",
					ProductImg: "/assets/Samsung/Samsung Phone.jpg",
					Ratting: "3/5",
				},
			],
			cart: [
				{
					Id: '12',
					Name: "Mi Lights",
					Brand: "Xiomi",
					ProductImg: "/assets/Xiomi/Mi Lights.jpg",
					Ratting: "5/5",
				},
				{
					Id: '13',
					Name: "Xiomi Wirless chargers",
					Brand: "Xiomi",
					ProductImg: "/assets/Xiomi/Xiomi Aircharger.jpg",
					Ratting: "5/5",
				},
				{
					Id: '14',
					Name: "Xiomi Phone",
					Brand: "Xiomi",
					ProductImg: "/assets/Xiomi/Xiomi Phone.jpg",
					Ratting: "5/5",
				},
			],
		},
		{
			name: "Dolon",
			password: "123455",
			product: [
				{
					productName: "Samsung Phone",
					price: "10K",
					rating: "5/5",
					brand: "Samsung",
				},
			],
			cart: [
				{
					productName: "Wolton Phone",
					price: "10K",
					img: "",
					rating: "5/4",
					brand: "Wolton",
				},
			],
		},
	],
	Store: [
		{
			Id: '01',
			Name: "Aplle Watch 7",
			Brand: "Apple",
			ProductImg: "/assets/Apple/Aplle Watch 7.jpg",
			Ratting: "4/5",
		},
		{
			Id: '02',
			Name: "Apple Laptop",
			Brand: "Apple",
			ProductImg: "/assets/Apple/Apple Laptop.jpg",
			Ratting: "4/5",
		},
		{
			Id: '03',
			Name: "Apple Watch",
			Brand: "Apple",
			ProductImg: "/assets/Apple/Apple Watch.jpg",
			Ratting: "5/5",
		},
		{
			Id: '04',
			Name: "iMouse",
			Brand: "Apple",
			ProductImg: "/assets/Apple/iMouse.jpg",
			Ratting: "4/5",
		},
		{
			Id: '05',
			Name: "iphone 10",
			Brand: "Apple",
			ProductImg: "/assets/Apple/iphone 10.jpg",
			Ratting: "4/5",
		},
		{
			Id: '06',
			Name: "Iphone 13",
			Brand: "Apple",
			ProductImg: "/assets/Apple/Iphone 13.jpg",
			Ratting: "5/5",
		},
		{
			Id: '07',
			Name: "Samsung Bud",
			Brand: "Samsung",
			ProductImg: "/assets/Samsung/Samsung Bud.jpg",
			Ratting: "4/5",
		},
		{
			Id: '08',
			Name: "Samsung Fold",
			Brand: "Samsung",
			ProductImg: "/assets/Samsung/Samsung Fold.jpg",
			Ratting: "4/5",
		},
		{
			Id: '09',
			Name: "Samsung Laptop",
			Brand: "Samsung",
			ProductImg: "/assets/Samsung/Samsung Laptop.jpg",
			Ratting: "5/5",
		},
		{
			Id: '10',
			Name: "Samsung Phone",
			Brand: "Samsung",
			ProductImg: "/assets/Samsung/Samsung Phone.jpg",
			Ratting: "3/5",
		},
		{
			Id: '11',
			Name: "Samsung S10",
			Brand: "Samsung",
			ProductImg: "/assets/Samsung/Samsung S10.jpg",
			Ratting: "5/5",
		},
		{
			Id: '11',
			Name: "Mi band",
			Brand: "Xiomi",
			ProductImg: "/assets/Xiomi/Mi band.jpg",
			Ratting: "5/5",
		},
		{
			Id: '12',
			Name: "Mi Lights",
			Brand: "Xiomi",
			ProductImg: "/assets/Xiomi/Mi Lights.jpg",
			Ratting: "5/5",
		},
		{
			Id: '13',
			Name: "Xiomi Wirless chargers",
			Brand: "Xiomi",
			ProductImg: "/assets/Xiomi/Xiomi Aircharger.jpg",
			Ratting: "5/5",
		},
		{
			Id: '14',
			Name: "Xiomi Phone",
			Brand: "Xiomi",
			ProductImg: "/assets/Xiomi/Xiomi Phone.jpg",
			Ratting: "5/5",
		},
		{
			Id: '15',
			Name: "Xiomi Poco",
			Brand: "Xiomi",
			ProductImg: "/assets/Xiomi/Xiomi Poco.jpg",
			Ratting: "5/5",
		},
		{
			Id: '16',
			Name: "Xiomi Scotters",
			Brand: "Xiomi",
			ProductImg: "/assets/Xiomi/Xiomi Scotters.jpg",
			Ratting: "5/5",
		},
		{
			Id: '17',
			Name: "Xiomi Smartremote",
			Brand: "Xiomi",
			ProductImg: "/assets/Xiomi/Xiomi Smartremote.jpg",
			Ratting: "5/5",
		},
		{
			Id: '18',
			Name: "Xiomi werless",
			Brand: "Xiomi",
			ProductImg: "/assets/Xiomi/Xiomi werless.jpg",
			Ratting: "5/5",
		},
	],
};
